services:
  postgres_db:
    image: postgres:15 
    container_name: flight_search_postgres
    restart: always
    environment:
      POSTGRES_USER: flightsearchuser
      POSTGRES_PASSWORD: abc12345
      POSTGRES_DB: flight_search_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 